version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pickaxe-db
      - POSTGRES_DB=pickaxe
    restart: always
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - "15672:15672"
    restart: always
  psocket:
    build:
      context: .
      dockerfile: Dockerfile.psocket
    restart: unless-stopped
    entrypoint:
      [
        "/app/start.sh"
      ]
    command: [ "/app/psocket" ]
  pickaxe:
    build:
      context: .
      dockerfile: Dockerfile.pickaxe
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - DB_SOURCE=postgresql://root:pickaxe-db@postgres:5432/pickaxe?sslmode=disable
      - SOCKET_ADDRESS=psocket:8081
    depends_on:
      - postgres
      - psocket
    restart: unless-stopped
    entrypoint:
      [
        "/app/wait-for.sh",
        "postgres:5432",
        "--",
        "/app/start.sh"
      ]
    command: [ "/app/pickaxe" ]
